### ISSUE TITLE
what is the difference to tmate's docker image

### ISSUE THREAD

**Issue by PackElend** [IvoNet/ivonet-docker#1]
what is the difference of this docker compared with https://hub.docker.com/u/tmate

**Comment by IvoNet** [comment]
Not really sure anymore as it has been 3 years ago that I created it. I do know that I created the Dockerfile myself based on what I needed at that time for this blog post: https://www.ivonet.nl/2017/02/28/Instant-Terminal-Screen-Sharing/. Hope that helps...

**Comment by PackElend** [comment]
ok thx for the reply.
So I ask at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/tmate-io for some feedback
