### ISSUE TITLE
Reconnecting... (Cannot authenticate server)

### ISSUE THREAD

**Issue by mhrznamn068** [IvoNet/ivonet-docker#2]
Reconnecting... (Cannot authenticate server) on client 

on server
tmate    | <5> [init] (tmate) Bootstrapping ssh client ip=172.16.20.5
tmate    | <2> [init] (tmate) fatal: Error polling ssh socket: Socket error: disconnected

**Comment by IvoNet** [comment]
This repo is not maintained anymore as you can read in the NOTE of the readme file
